const itemService = require("../services/itemService");

const items = [
  {
    device: "Cellphone",
    brand: "Motorola",
    model: "G20",
    color: "Black",
    userId: 1,
    categoryId: 1,
    officeId: 2,
  },
  {
    device: "Cellphone",
    brand: "Motorola",
    model: "G20",
    color: "Black",
    userId: 2,
    categoryId: 1,
    officeId: 2,
  },
  {
    device: "Cellphone",
    brand: "Samsung",
    model: "GalaxyS22",
    color: "Black",
    userId: 3,
    categoryId: 1,
    officeId: 2,
  },
  {
    device: "Laptop",
    brand: "Dell",
    model: "Latitude7280",
    color: "Black",
    userId: 1,
    categoryId: 1,
    officeId: 2,
  },
  {
    device: "Laptop",
    brand: "BGH",
    model: "PositivoZ210",
    color: "Gray",
    userId: 2,
    categoryId: 1,
    officeId: 2,
  },
  {
    device: "Laptop",
    brand: "Lenovo",
    model: "ThinkpadE14",
    color: "Black",
    userId: 3,
    categoryId: 1,
    officeId: 2,
  },
  {
    device: "Mouse",
    brand: "Fujitsu",
    model: "M420NB",
    color: "Black",
    userId: 1,
    categoryId: 1,
    officeId: 2,
  },
  {
    device: "Mouse",
    brand: "Microsoft",
    model: "W1000",
    color: "Black",
    userId: 2,
    categoryId: 1,
    officeId: 2,
  },
  {
    device: "Mouse",
    brand: "Logitech",
    model: "M100",
    color: "Gray",
    userId: 3,
    categoryId: 1,
    officeId: 2,
  },
  {
    device: "Printer",
    brand: "HP",
    model: "Deskjet2675",
    color: "White",
    userId: 1,
    categoryId: 1,
    officeId: 2,
  },
  {
    device: "Printer",
    brand: "HP",
    model: "Deskjet2675",
    color: "White",
    userId: 2,
    categoryId: 1,
    officeId: 2,
  },
  {
    device: "Keyboard",
    brand: "Microsoft",
    model: "600",
    color: "Black",
    userId: 1,
    categoryId: 1,
    officeId: 2,
  },
  {
    device: "Keyboard",
    brand: "Microsoft",
    model: "600",
    color: "Black",
    userId: 2,
    categoryId: 1,
    officeId: 2,
  },
  {
    device: "Keyboard",
    brand: "Microsoft",
    model: "600",
    color: "Black",
    userId: 3,
    categoryId: 1,
    officeId: 2,
  },
  {
    device: "Headphones",
    brand: "Motorola",
    model: "Escape200",
    color: "Black",
    userId: 1,
    categoryId: 1,
    officeId: 2,
  },
  {
    device: "Headphones",
    brand: "Motorola",
    model: "Escape200",
    color: "Black",
    userId: 2,
    categoryId: 1,
    officeId: 2,
  },
  {
    device: "Chair",
    brand: "Sate",
    model: "A8705",
    color: "Black/Red",
    userId: 1,
    categoryId: 1,
    officeId: 2,
  },
  {
    device: "Chair",
    brand: "Sate",
    model: "A8705",
    color: "Black/Red",
    userId: 2,
    categoryId: 1,
    officeId: 2,
  },
  {
    device: "Chair",
    brand: "Mesch",
    model: "JX-1602",
    color: "Black",
    userId: 3,
    categoryId: 1,
    officeId: 2,
  },
];

async function createItems() {
  for (let i = 0; i < items.length; i++) {
    let item = items[i];
    await itemService.createItem(item);
  }
  console.log("ITEMS created");
}

module.exports = createItems;
